config/routes.rb
Boxroom::Application.routes.draw do
  get '/file_exists', :to => 'files#exists'
  get '/signin', :to => 'sessions#new', :as => 'signin'
  delete '/signout', :to => 'sessions#destroy'

  # Resources
  resources :admins, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :reset_password, :except => [:index, :show, :destroy]
  resources :signup, :only => [:edit, :update]
  resources :groups, :except => :show
  resources :files, :except => [:index, :new, :create]
  resources :share_links, :only => [:index, :show, :destroy]

  resources :users, :except => :show do
    put :extend, :on => :member
  end

  resources :clipboard, :only => [:create, :destroy] do
    post :copy, :on => :member
    post :move, :on => :member
    put :reset, :on => :member
  end

  # Update a collection of permissions
  resources :permissions, :only => :update_multiple do
    put :update_multiple, :on => :collection
  end

  # Nested resources
  resources :folders, :shallow => true, :except => [:new, :create] do
    resources :folders, :only => [:new, :create]
    resources :files, :only => [:new, :create]
  end

  resources :files, :shallow => :true, :only => :show do
    resources :share_links, :only => [:new, :create]
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "folders#index"
end

app/views/shared/_footer.html.erb
<div id="footer">
  <p class="footer">
    <a href="http://boxroomapp.com/">Boxroom</a> is released under the <a href="http://boxroomapp.com/license">MIT license</a>
  </p>
</div>

app/views/shared/_header.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><%= image_tag('logo.png', :alt => 'Boxroom') %></a>
    </div>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <% if signed_in? -%>
          <li><%= link_to t(:folders), folders_path %></li>
          <% if current_user.member_of_admins? -%>
            <li><%= link_to t(:users), users_path %></li>
            <li><%= link_to t(:groups), groups_path %></li>
            <li><%= link_to t(:shared_files), share_links_path %></li>
          <% end -%>
        <% end -%>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? -%>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= fa_icon "user", text: current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                  <%= link_to fa_icon("cogs", text: t(:settings)), edit_user_path(current_user) %>
                  <%= link_to fa_icon("power-off", text: t(:sign_out)), signout_path, :method => :delete %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>